server:
  port: 0

spring:
  application:
    name: orders

kafka:
  producer:
    bootstrap-servers: localhost:9092
    acks: all
    delivery-timeout-ms: 120000
    linger-ms: 0
    request-timeout-ms: 30000
    ennable-idempotence: true
    retries: 2
    maximum-in-flight-requests-per-connection: 5
  topic:
    orders:
      name: order-created-topic
      partitions: 3
      replicas: 3

#logging:
#  level:
#    org.apache.kafka: ERROR
